[project]
name = "onchainkms-stacks"
description = "Track your activity sport onchain"
authors = []
telemetry = true
cache_dir = "./.cache"

# [contracts.onchainkms-stacks]
# path = "contracts/onchainkms-stacks.clar"

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
